name: Deploy

on:
  push:
    branches:
      - main

env:
  VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
  VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
  VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
  VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
  VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
  VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Node
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: production-files
          path: ./dist
          retention-days: 1  # Optional: Set retention days for the artifact

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
